[package]
name = "ftree"
version = "1.2.0"
edition = "2021"
documentation = "https://docs.rs/ftree/"
repository = "https://github.com/brurucy/ftree"
license = "Apache-2.0 OR MIT"
description = "A very fast fenwick tree implementation"
keywords = ["sum", "prefix", "fenwick", "tree", "nostd"]
categories = ["data-structures"]
readme = "README.md"


[dependencies]
serde = { version = "1.0.151", features = ["derive"] }
rkyv = { git = "https://github.com/praveenperera/rkyv", branch = "0.7", features = [
    "indexmap",
    "validation",
    "strict",
]}
[dev-dependencies]
ntest = "0.9"